### ISSUE TITLE
Error when taking order

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#713]
https://airswap-web-dev.herokuapp.com/#/order/KwGgDAHgogbFAcAmAjAMQCwHZMDN4E5EBhZZMAQWE3mGUzEURkXyOAFMd9qAjGEZDEyJs1OgGZ4-QcLHo64CEnHoAQukTiYPcumBgw4nIygdEPRAEMihfDCoxVYGkUSKw1ewGMY7eJh58HHpEYGBxbHYGdEsvdhgYcTAvZHZLSwicAQMcsBBMd1yi4pLSssVMfC98fS9MdHRtTRiYSwATcMDnHB4cFXMwZC90NobpYpARRXCkET90fBqyPmBE9Dj2HkFGKPZxRC9afEst1LaYQTAeFR4eDPgNcXE2umB4RSxOTBSOBvZEGiIK5tIyGE7oMDACGWKT+NqWMBcfRherzSwQwateDIHijPA8IA

SwapERC20.ts:52 Uncaught (in promise) TypeError: (0 , utils_1.checkResultToErrors) is not a function
    at SwapERC20.<anonymous> (SwapERC20.ts:52:1)
    at step (MakerRegistry.ts:10:1)
    at Object.next (MakerRegistry.ts:10:1)
    at fulfilled (MakerRegistry.ts:10:1)

**Comment by piersss** [comment]
All packages up to date:
    
    "@airswap/balances": "2.0.2",
    "@airswap/constants": "3.0.4",
    "@airswap/libraries": "3.3.4",
    "@airswap/maker-registry": "3.1.4",
    "@airswap/metadata": "3.0.8",
    "@airswap/swap-erc20": "3.0.1",
    "@airswap/typescript": "3.0.2",
    "@airswap/utils": "3.0.5",

**Comment by piersss** [comment]
This is fixed with the latest protocols release
